### ISSUE TITLE
No mapping found for toggl tag xxxx

### ISSUE THREAD

**Issue by aiopa** [eiriksm/toggl-to-tripletex#32]
Hello @eiriksm 

Thank you for making this. I was just starting on the same thing. I hate handling my hours. 

I am trying to get this to work. I am having some issues with toggl tags. There is someting i am missing here, but when i try to mapp the tags, i am not sure what numeric activity id i need. 

If i remove the tag in toggle i get the error "No tag supplied for activity", and if i add a tag i am getting No mapping found for toggl tag xxxx 

I have tried the activityId in tripletex, id and wid in toggl tag. I have also tried the id on the left side of the activity, and not all of my activities have this.

``` 
"mappings": {
      "xxx": { //PID from toggl. Found in response when trying to run the app without it
        "name": "Project name in tripletex",
        "id": "Tripletex project id"
      }
    },
    "activityMappings": {
      "toggl-tag": "xxx" //unserten what to putt in here. 
    }
``` 

Also is there a easy way to find this info? as of now i am inspecting the tripletex tables to find the ids.

**Comment by aiopa** [comment]
I see travis is having the same issue? 

https://travis-ci.org/eiriksm/toggl-to-tripletex/jobs/495147142

No tag supplied for activity: Test without tag

**Comment by aiopa** [comment]
So i found my issue "toggl-tag" Has to be the name of the tag you make in toggle. 

The number for this tag is the activityID of the activity in Tripletex

**Comment by eiriksm** [comment]
hah!

Wow, did not expect anyone to find this useful, except my co-workers.

First of all, that is not the reason travis is failing, no.

Second: toggl-tag is the name in toggl, yes.
The number is the activity ID. For me this is numeric for all activities. Since you found out, you probably have those as well?

Third: Tripletex changed something in their javascript, so the master branch does not work very well. You should use the branch called `feat/pup` where its completely rewritten to use puppeteer/chrome instead of the mammoth old phantomjs. I have not yet gotten around to fix up the tests for that branch, so I have not merged it yet. Especially since I did not expect anyone ever to find this useful :p

Have a great weekend.
